### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by CarlosRubioTNM** [heatsii/PresentacionDailySoft#1]
Muy bien, jóvenes. Quedó bien la animación que usaron.

Les encargo que realicen los siguientes cambios:
- Arreglen los enlaces para que redireccionen correctamente a las páginas de los integrantes.
- Añadan en la página principal un párrafo inventado sobre la historia de su empresa.
- La lista de integrantes requiere que los nombres queden más grandes.

Espero su respuesta.

**Comment by KiraBelak** [comment]
Los cambios se han echo, sin querer le di commit en vez de pull

**Comment by CarlosRubioTNM** [comment]
@KiraBelak Entonces los cambios están hechos en el branch issue1. Necesitan hacer el proceso de pull request y merge para que se aplique todo a la rama principal y terminar la práctica. Saludos.

**Comment by heatsii** [comment]
Ya se realizó el pull request con el merge, los cambios se integraron a la main branch.

**Comment by CarlosRubioTNM** [comment]
Ok, listo. Buen trabajo, jóvenes. 👍
